# TCL File Generated by Component Editor 13.0sp1
# Mon Oct 20 22:57:57 BRST 2025
# DO NOT MODIFY


# 
# NiosAndUserHW "NiosAndUserHW" v1.0
#  2025.10.20.22:57:57
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module NiosAndUserHW
# 
set_module_property DESCRIPTION ""
set_module_property NAME NiosAndUserHW
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME NiosAndUserHW
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file NiosAndUserHW.vhd VHDL PATH NiosAndUserHW.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 

